#!/bin/sh
    pushd build-monitor-plugin
    MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=2048m" mvn clean && MAVEN_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9000" mvn hpi:run -Dhudson.Main.development=true -Djetty.port=8090
    popd